src/sheets/queries.py
Les brouillons sont filtrés pour les BSDD en se basant sur la valeur de `status`. J'ai rajouté un filtre pour les autres bordereaux qui utilise la valeur de `is_draft`.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-11633)
=> Adds filter for other bordereaux than bsdd

src/sheets/graph_processors/html_components_processors.py
Je propose de passer à un chiffre après la virgule pour éviter les arrondis qui peuvent induire en erreur.
Avant :
Après :
---
=> Adds more precision for stock numbers

changelog.md, src/sheets/graph_processors/html_components_processors.py, src/templates/sheets/components/stats_graph.html
Ajoute le temps de traitement moyen (en nombre de jours) pour les bordereaux dont le traitement a duré plus d'un mois.
Exemple :
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-11747)
=> Adds first implementation of mean processing time

changelog.md, src/sheets/templatetags/graph_tags.py, src/templates/sheets/components/traceabilty_break.html, src/templates/sheets/components/waste_is_dangerous_statements.html, src/templates/sheets/sheetpdf.html
Cette PR corrige le problème de certains tableaux qui étaient coupés en version PDF car ils n'avaient pas la bonne classe CSS.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-11827)
=> Tra-11827/fix-traceability-breaks-pdf

changelog.md, src/sheets/data_processing.py, src/sheets/database.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/queries.py, src/templates/sheets/components/stats_graph.html
Cette PR ajoute une granularité "contenant" aux statistiques BSFF. Ainsi, pour le BSFF, les quantités entrantes/sortantes sont calculées à partir des données des contenants liés aux bordereaux. De même l'on calcule deux nouvelles statistiques dans le composant des données sur l'année.
Exemple :
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-11325)
=> Adds packaging data to BSFF stats

src/sheets/graph_processors/html_components_processors.py
Corrige un bug qui impacte les BSVHU pour lesquels le champ `waste_name` n'existe pas.
=> Fixes a bug for VHU in Outliers Component

src/sheets/graph_processors/html_components_processors.py
Si les codes déchets ne sont pas rentrés au bon format sur les bordereaux, la description associée au code déchet n'est pas retrouvée et donc on se retrouve avec un "NaN" non serializable. Ce hotfix remplace les NaN par des chaînes vides.
=> Handles NaN in waste description

src/sheets/graph_processors/html_components_processors.py
Une typo empêchait l'affichage des dates de réception dans le tableau des bordereaux avec des quantités aberrantes.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-12339)
=> Fixes received_at being NA for quantity outliers

src/sheets/graph_processors/html_components_processors.py, src/sheets/tests/test_bsd_stats_processor.py
Le composant de déchets sur site n'affiche maitnenant que les déchets dangereux.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-12946)
=> Ne plus afficher les déchets non dangereux dans les déchets sur site

src/sheets/graph_processors/html_components_processors.py
Cette PR résous un problème qui empêche l'édition de la fiche lorsque le code déchet associé à un bordereau n'existe pas et/ou est mal formaté.
---
=> Fills NaN values for storage component

src/sheets/graph_processors/plotly_components_processors.py
Les lignes contenants des NaT sont maintenant écartées dans `WasteProcessingWithoutICPEProcessor`.
---
=> HOTFIX - Corrige un bug lorsqu'il y a prséence de NaT dans BSFF packagings

src/sheets/data_processing.py, src/sheets/database.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/queries.py, src/sheets/tests/test_bsd_stats_processor.py, src/templates/sheets/components/bs_without_icpe_authorization_tables.html, src/templates/sheets/components/bsd_canceled_table.html, src/templates/sheets/components/bsda_worker_bordereaux_counts_stats.html, src/templates/sheets/components/bsda_worker_bordereaux_durations_stats.html, src/templates/sheets/components/followed_with_pnttd_table.html, src/templates/sheets/components/gistrid_stats_table.html, src/templates/sheets/components/icpe.html, src/templates/sheets/components/linked_companies.html, src/templates/sheets/components/private_individuals_collections_table.html, src/templates/sheets/components/quantity_outliers_table.html, src/templates/sheets/components/same_emitter_recipient_table.html, src/templates/sheets/components/traceabilty_break.html, src/templates/sheets/components/transported_bordereaux_stats.html, src/templates/sheets/components/waste_flows_table.html, src/templates/sheets/components/waste_is_dangerous_statements.html, src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
Cette PR permet de prendre en compte le nouveau modèle de données de l'application Trackdéchets dans lequel maintenant les transporteurs BSDA sont stockés à part.  
Correction aussi d'un bug lorsque il y a des BSFF mais sans emballages, ils sont écartés.
Enfin optimisation de la mise en page des tableaux très larges en annexe.
---
=> Add BSDA transporter data

src/sheets/graph_processors/html_components_processors.py
Le calcul des stats n'était pas fait pour les BSFF suite à une typo dans le code.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14044)
=> Correction d'une erreur dans le calcul des stats BSFF

src/sheets/graph_processors/html_components_processors.py
Les déchets sortants BSDA n'apparaissaient plus dans le tableaux des flux car la date d'envoi/prise en charge transporteur n'est plus présente dans la table des BSDA suite au passage au multmodal. 
Le changement avait été déjà pris en compte dans les autres composants en s'appuyant sur la date de signature transporteur plutôt que la date déclarative de prise en charge comme pour les autres bordereaux.
La même stratégie est maintenant utilisée pour le composant `BsdStatsProcessor`.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14132)
=> Corrige un bug qui empéchait les déchets sortants BSDA d'apparaitre dans le tableaud es flux de déchets

src/sheets/graph_processors/html_components_processors.py
Un index portait le même nom qu'une colonne dans un dataframe pandas dans le composant `FollowedWithPNTTDTableProcessor` faisant planter le tri à la fin du traitement de données.
Le nom de l'index est maintenant supprimé.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14377)
=> Correction d'un bug sur le composant FollowedWithPNTTDTableProcessor

src/sheets/queries.py
Il restait quelques colonnes relative aux transporteurs dans la requpete des données BSDA.
Cette PR les supprime.
Les données de transport BSDA sont maintenant extraites de la table `bsda_transporter`.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14404)
=> Supression des dernières colonnes transporteurs de la table BSDA

src/sheets/queries.py
Pandas a une [limitation](https://pandas.pydata.org/pandas-docs/version/1.5/user_guide/timeseries.html#timestamp-limitations) sur les dates.
Pour éviter les *overflows* qui font planter la fiche, les bordereaux ayant des dates aberrantes sont filtrés en amont.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14486)
=> Ajout de filtres de dates aux requêtes pour éviter les overflows sur kes dates

src/sheets/graph_processors/html_components_processors.py
Dans le cas du transport multimodal, la colonne `quantity_received` n'était pas sélectionnée et donc manquant au moment des étapes suivantes.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14594)
=> Correction d'un bug sur le QuntityOutliersProcessor

src/sheets/views/sheet_views.py, src/templates/sheets/components/waste_flows_table.html, src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
L'encart explicatif du header a été changé avec la date de mise à jour de chaque données.
Le composant affichant la liste des déchets non dangereux marqués commé étant dangereux a été remontée.
De plus, correction d'un problème qui faisait qu'une page blanche état ajouté à la fin du PDF.
---
- [TRA-14587](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14587)
- [TRA-14595](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14595)
- [TRA-14590](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14590)
=> Changement esthétiques et correction d'un problème avec le PDF

changelog.md, src/sheets/data_processing.py, src/sheets/database.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/queries.py
De la même manière que les BSDD et BSDA, on affiche les révisions pour les BSDASRI ainsi que les BSDASRI annulés.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14566)
=> Ajout des requêtes de révision pour les BSDASRI

src/sheets/graph_processors/plotly_components_processors.py
Le traitement des données échoue si le dataframe est vide après le filtrage de la date en raison d'un index qui n'est pas de type datetime.
Le filtrage est maintenant traité en amont et l'aggrégation n'est effectuée que s'il reste des données.
=> HOTFIX - Bug sur le composant BsdaWorker 

src/sheets/data_processing.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/queries.py, src/sheets/templatetags/utils.py
Les données de transport BSDA n'étaient pas récupérées pour les entreprises de travaux ce qui entrainaient un bug. 
De plus il manquait des filtres dans la fonction de traitement des données du composant `BsdaWorkerStatsProcessor`.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14934)
=> Correction d'un bug sur le composant dédié aux entreprises de travaux

src/sheets/data_processing.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py
Jusqu'à présent certains Processors n'avaient pas été migrés suite à l'ajout du multimodal et utilisaient une logique différente pour se passer des données de transport tout en continuant à produire les transformations.
Ces composants utilisent maintenant les données de transport.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14940)
=> Ajout de la logique de transformation pour les bordereaux avec le multimodal sur les Processors

src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/tests/test_icpe_annual_item_processor.py, src/sheets/tests/test_waste_processing_without_icpe_rubrique_processor.py
Un bug a été résolu sur le composant `ICPEAnnualItemProcssor` lorsque l'établissement avait un seul point de donnée sur une rubrique particulière.
La logique et la robustesse du traitement de données du composant `WasteProcessingWithoutICPERubriqueProcessor` a été revue également.
Enin des tests ont été ajoutés pour ces deux composants.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15027)
=> Correction de bugs sur les composants ICPE

src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/tests/constants.py, src/sheets/tests/expected/incinerator_outgoing_waste_build_data_expected.json, src/sheets/tests/test_incinerator_outgoing_waste_processor.py, src/sheets/tests/test_waste_flows_table_processor.py
Le processor plantait en cas d'incinérateur sans aucune donnée après application des filtres.
Correction d'une erreur de logique qui rendait la mauvaise valeur pour `_check_data_empty` du `IncineratorOutgoingWasteProcessor`.
Ajout de tests pour `IncineratorOutgoingWasteProcessor`.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15266)
=> Correction d'un bug dans IncineratorOutgoingWasteProcessor

src/sheets/data_processing.py
Les révisions n'étaient pas affichées car l'ID de l'établissement n'était pas peuplé avant la requête sur la table des révisions.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15341)
=> Corrige un problème sur les révisions de bordereaux

.github/workflows/main.yml, changelog.md, src/.env.dist, src/config/settings/base.py, src/config/settings/dev.py, src/roadcontrol/constants.py, src/roadcontrol/converters.py, src/roadcontrol/forms.py, src/roadcontrol/td_requests.py, src/roadcontrol/templatetags/road_control_tags.py, src/roadcontrol/tests/test_converters.py, src/roadcontrol/views.py, src/templates/roadcontrol/partials/_bsd_card.html
La fiche établissement exploite la query bsds pour effectuer des recherches par siret (transporteur), plaque ou readableId sur l'ensemble des bsds.
L'introduction de l'onglet retour nécessitait soit de modifier cette query avec des filtres qui s'intégraient mal avec l'existant (le bsd doit porter la plaque xyz et être dans un onglet collecté ou retour, le siret n'étant pas fourni en paramètre).
Il a été jugé plus pertinent d'écrire une query spécialisée et simplifiée: controlBsds, réservée aux users rattachés à un compte gouvernemental disposant des perms adéquates.
La fiche établissement permet désormais d'utiliser cette query via la variable USE_CONTROL_BSDS_QUERY
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-14965)
=> Use new controlbsd query

src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/tests/test_rndts_quantities_graph_processor.py, src/sheets/tests/test_rndts_statements_graph_processor.py, src/sheets/tests/test_rndts_stats_processor.py
Les données SSD n'ont pas de SIRET producteur bien que ce soit considéré comme un registre "sortant" dans le traitement des données. Maintenant, un test est utilisé pour sélectionner la bonne colonne.
Aussi des tests ont été ajoutés pour le `RNDSStatsProcessor`
---
=> Corrige un bug pour les données SSD

src/sheets/queries.py
Lorsque qu'un producteur est mentionné dans des bordereaux d'annexe 1 (bordereaux enfants), il n'y a pas la possibilité d'extraire la quantité pesée à l'arrivée car seul le bordereau chapeau a une quantité pesée.
Dans ce cas précis, on utilise de manière transparente la quantitée estimée au départ pour les différents composants.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14467)
=> Utilisation de la quantité estimée pour les bordereaux d'annexe 1

changelog.md, src/roadcontrol/forms.py
Corrige la validation de la longueur du chap de recherche par plaque, qui nécessitait plus de 6 caractères (>) quand le siret n'est pas fourni (hors tirets et espace) et passe à 6 inclus (>=)
Pb décelé dans le cadre du ticket cité en référence
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-15658)
=> Fix plate length control

src/templates/scripts/registry_form_submit.html
El patron trouvait gênant que le message reste affiché et le bouton disabled, on laisse affiché qq secondes seulement.
https://github.com/user-attachments/assets/42277e45-6a6d-4b51-99ea-7facd320200e
---
=> Masque la mention de téléchargement de registre après un délai.

src/sheets/graph_processors/plotly_components_processors.py, src/sheets/tests/test_bsd_quantites_graph.py
La génération du composant plantait si les données de contenants BSFF avaient l'ensemble de leurs dates d'acceptation vides/NA. 
Ajout de tests sur le composant.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15992)
=> Correction d'un bug sur le composant BsdQuantitiesGraph avec BSFF

Procfile
Le paramètre `--pool threads` était manquant est crée des problèmes en prod.
---
=> Corrige un paramètre manquant pour le workerapi dans le procfile

changelog.md, src/accounts/admin.py, src/config/settings/base.py, src/oidc/backends.py, src/oidc/tests/test_proconnect.py, src/templates/oidc/proconnect_authentication_error.html
La création d'users lors du premier login proconnect était désactivée pour ne pas donner accès à toute la Gendarmerie. Il s'avère que ce n'est pas un problème, on réactive donc.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-16188)
=> Proconnect oidc workflow creates gendarmerie users

changelog.md, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/queries.py, src/sheets/tests/test_icpe_annual_item_processor.py
Jusqu'à présent l'objectif de quantité traitée était égal à la moitié de la quantité autorisée. Dorénavant il est basé sur une valeur que l'administration nous fournit.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-16353)
=> Ajout de l'objectif de quantité traitée pour 2025 pour les installations 2760-2

src/sheets/templatetags/graph_tags.py, src/templates/sheets/components/icpe_graphs.html, src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
Avant touts les blocs de graphes ICPE s'affichaient pour chaque fiche.
Avec cette PR, l'affichage du bloc n'est activé que si l'établissement a la rubrique qui correspond.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-16162)
=>  Rendre l'affichage des graphes ICPE dynamique

CONTRIBUTING.md, src/accounts/constants.py, src/accounts/menus.py, src/common/mixins.py, src/roadcontrol/tests/test_views.py, src/roadcontrol/urls.py, src/roadcontrol/views.py, src/templates/roadcontrol/partials/_bsd_card.html
Corrige les permissins d'accès pour l'inspection du travail au niveau du téléchargement de bsd.
La pr corrige un bug sur la liste des permissions de la vue de download, et renomme certaines variables et vues pour les rendre plus explicites.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-16766)
=> Fix pdf download perms

src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-16823)
=> Enlever mention dangereux des sheets comprenant des déchets ND et TEXS
