MTES-MCT/trackdechets-vigiedechets

.gitignore, Pipfile, Pipfile.lock, src/.env.dist, src/sheets/graph_processors/html_components_processors.py, src/templates/sheets/components/stats_graph.html
J'ai revu le composants avec les retours de l'administration, dis moi ce que tu en penses :
=> Modifies the BS Stat component

src/sheets/data_processing.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/templates/sheets/sheet.html
Corrige le problème qui faisait que l'on affichait le message "PAS DE DONNÉES POUR LE SIRET XXX" alors qu'il y avait bien des données.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-11745)
=> Fixes data is empty bug

src/sheets/graph_processors/html_components_processors.py
Un des tests pour détecter l'absence de données ne fonctionnait pas dans un cas particulier.
Ajout aussi d'un autre test sur une des fonctions de pré-traitement.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-12024)
=> Updates test for empty data

.buildpacks
=> Add locales buildpack

.buildpacks
=> Add python buildpack

src/templates/sheets/components/traceabilty_break.html
Un espace manquant cassait le layout
---
=> Corrige la mise en page qui affichait des tabelaux décentrés

Pipfile, Pipfile.lock, src/config/settings/base.py, src/config/settings/dev.py, src/config/settings/production.py
Envoi des mails avec Sendinblue/Brevo
=> Send mail through brevo

src/sheets/database.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/queries.py, src/templates/sheets/components/icpe.html
Le schéma de la table des données ICPE a changé, je fais ce hotfix en attendant de faire quelque chose de plus propre @providenz
=> HOTFIX - Mise à jour suite au changement de schema des données ICPE en base

src/sheets/queries.py
Hotfix suite à un changement de schéma.
=> Updates ICPE query

src/sheets/queries.py
=> Updates query filter

src/sheets/database.py
=> Fix agreement data error

.github/workflows/main.yml, src/accounts/templatetags/form_helpers.py, src/sheets/forms.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/models.py, src/sheets/tests/test_views.py, src/static/css/style.css
=> Form period validation

src/sheets/graph_processors/html_components_processors.py, src/sheets/tests/test_bsd_stats_processor.py
Ajoute des tests sur le composant BsdStatsProcessor
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-11660)
=> Adds first tests to bsdstatsprocessor

src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/tests/test_bsd_stats_processor.py
Le composant plantait pour les BSDASRI.
---
=> Résoud un problème sur le composant ICPE

src/sheets/graph_processors/html_components_processors.py
Corrige le calcul du stock total de déchets dangereux sur site.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-13161)
=> Corrige le calcul du stock total

.github/workflows/main.yml, Pipfile, Pipfile.lock, changelog.md, pyproject.toml, src/accounts/tests/test_views.py, src/lint.sh, src/sheets/data_processing.py, src/sheets/database.py, src/sheets/graph_processors/html_components_processors.py, src/templates/base.html, src/templates/emails/second_factor/second_factor.html, src/templates/private_home.html
=> Update deps and switch to py311 &  ruff

src/sheets/queries.py
Les requêtes vers bsdd_transporter ont été reroutées vers la table bsdd_transporter_enriched ce qui améliore les performances
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-13726)
=> Amélioration des performances sur les requêtes de données transporteur

src/config/urls.py, src/content/tests/test_views.py, src/templates/base.html
=> Remove warning banner and disable admin login url

src/templates/accounts/password_reset_confirm.html
=> Ajoute un texte explicatif lorsque le lien de réinit de mot de passe est invalide

src/sheets/data_processing.py, src/sheets/graph_processors/html_components_processors.py
Cette PR corrige un bug qui faisait planter le calculd es données dans le cas où l'étblissement transporte des BSFF.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-13792)
=> Correction d'un bug dans le cas du transport de BSFF

src/sheets/database.py, src/sheets/graph_processors/plotly_components_processors.py, src/templates/base.html, src/templates/base_pdf.html, src/templates/emails/invitation/welcome.html, src/templates/emails/password_reset/body.html, src/templates/emails/second_factor/second_factor.html, src/templates/emails/second_factor/second_factor.txt, src/templates/sheets/prepare.html, src/templates/sheets/sheetpdf.html
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-13889)
=> Rename app to Fiche établissement

src/templates/accounts/login.html, src/templates/content/_rename_banner.html, src/templates/public_home.html
Ajoute un texte expliquant le changement d'url et de nom.
---
=> Add renaming disclaimer

src/sheets/plotly_utils.py, src/sheets/views.py, src/static/css/style.css, src/templates/sheets/components/bs_without_icpe_authorization_tables.html, src/templates/sheets/components/followed_with_pnttd_table.html, src/templates/sheets/components/gistrid_stats_table.html, src/templates/sheets/components/icpe.html, src/templates/sheets/components/linked_companies.html, src/templates/sheets/components/traceabilty_break.html, src/templates/sheets/components/waste_flows_table.html, src/templates/sheets/components/waste_is_dangerous_statements.html, src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
PR de changements esthétiques pour réorganiser les blocs et les niveaux de titre afin d'avoir une meilleure cohérence.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-13813)
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-13815)
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-13814)
=> Réorganisation de la mise en page

src/config/settings/base.py
=> Correction de l'objet du mail otp

src/templates/sheets/components/transported_bordereaux_stats.html, src/templates/sheets/sheetpdf.html
Petite PR pour revoir la formulation des titres qui incluaient "sur l'année" et correction d'une petite coquille pour les BSD non dangereux transportés.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14050)
=> Reformulation et correction d'une coquille

changelog.md, src/sheets/graph_processors/html_components_processors.py, src/sheets/queries.py, src/sheets/tests/test_bsd_stats_processor.py, src/templates/sheets/components/stats_graph.html, src/templates/sheets/sheet.html
Ajoute une nouvelles statistiques sur le nombre de demandes révisions crées par l'établissement pour lequel on édite la fiche et étant en attente d'acceptation.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-13940)
=> Ajoute le nombre de révisions en cours

src/aiot_provider/adapter.py
Permet l'accès au lecteurs GUN (admin centrale)
=> Allow more profiles

src/sheets/forms.py, src/sheets/tests/test_views.py, src/sheets/views/sheet_views.py, src/templates/sheets/prepare.html
Corrige la validation des dates de requêtes
---
=> Fix registry form

src/aiot_provider/provider.py, src/config/settings/base.py, src/templates/temp_aiot_login_page.html
=> Allow configurable oidc scopes

src/config/settings/base.py
=> Fix settings

Procfile
=> Fix procfile

Pipfile, Pipfile.lock, cron.json, src/aiot_provider/adapter.py, src/config/settings/base.py
=> Library rollback

src/sheets/admin.py, src/templates/admin/recent_sheets.html
Petites améliorations de l'admin:
- affichage du nom des établissements
- utilisation de only pour limiter les colonnes chargées
- correction de l'affichage des dernieres fiches créées
---
=> Improve sheet admin

src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
Micro-PR pour afficher la dernière date de mise à jour des données GISTRID.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14700)
=> Ajout de la date de dernière mise à jour des données GISTRID

src/sheets/queries.py
Suite au changement du schéma de données RNDTS, changement du nom des tables sources.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14701)
=> Changement du nom des tables RNDTS

src/config/settings/production.py, src/templates/sheets/components/bs_without_icpe_authorization_tables.html
Force quelques réglages de sécurité et réduit les sessions à 4 heures
---
=> Enhance security settings

.github/workflows/main.yml, Pipfile.lock, changelog.md, src/aiot_provider/adapter.py, src/aiot_provider/signals.py, src/aiot_provider/tests/test_aiot_auth_workflow.py, src/config/settings/tests.py, src/conftest.py, src/sheets/tests/test_views.py, src/sheets/views/views.py
Ajoute des tests sur le workflow monAIOT
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-14659)
=> Mon aiot test auth workflow

src/sheets/graph_processors/html_components_processors.py
Dans un cas particulier, un test était effectué sur une variable qui n'existait pas encore.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14814)
=> Hotfix d'un bug sur le composant d'alerte ICPE

src/sheets/constants.py, src/sheets/data_processing.py, src/sheets/database.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/utils.py
Réorganisation du module `data_processing.py`. Les méthodes ont été redécoupées et réorganisées.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14600)
=> Refactoring du module data processing

src/templates/sheets/sheetpdf.html
Les sous profils avait été ajouté à la version web mais pas à la version PDF, c'est maintenant chose faite !
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14909)
=> Ajout es sous-profils au PDF

src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
Les données ont été rafraichies, la nouvelle pèriode a été ajoutée au template.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14916)
=> Modificiation de la date de mise à jour des données GUN et RNDTS

Pipfile, Pipfile.lock, src/aiot_provider/adapter.py, src/aiot_provider/provider.py, src/aiot_provider/tests/test_aiot_auth_workflow.py, src/aiot_provider/tests/test_allauth_disabled_views.py, src/aiot_provider/views.py, src/config/settings/base.py, src/config/urls.py, src/templates/404.html, src/templates/500.html
Met à jour les dépendances OpenID
Ajoute des pages par défaut pour les 400 et 500
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-14913)
=> Update allauth and enhance tests

src/sheets/tests/test_private_individuals_collections_table_processor.py
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-14941)
=> Ajout de tests au PrivateIndividualsCollectionsTableProcessor

src/sheets/graph_processors/html_components_processors.py
Bug d'arrondi à cause d'un type non float corrigé par une conversion de type avant l'arrondi.
---
=> Correction d'un bug lors de l'arrondi

changelog.md, src/sheets/database.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/queries.py, src/sheets/tests/test_private_individuals_collections_table_processor.py, src/sheets/tests/test_ssd_processor.py, src/templates/sheets/components/ssd_table.html, src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
Le composant `SSDProcessor` affiche maintenant, pour chaque déchet, la nature de la sortie de statut de déchets.
Des tests pour le composant ont été ajoutés.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15001)
=> Mis à jour du SSDProcessor

src/roadcontrol/forms.py, src/roadcontrol/models.py, src/templates/roadcontrol/bundle_result.html, src/templates/roadcontrol/roadcontrol.html
=> Post review fixes

src/roadcontrol/converters.py, src/roadcontrol/td_requests.py, src/roadcontrol/tests/test_converters.py, src/sheets/tests/test_icpe_annual_item_processor.py, src/sheets/tests/test_waste_processing_without_icpe_rubrique_processor.py, src/templates/roadcontrol/partials/_bsd_card.html
Affiche le siret  transporteur sur les cartes bsds
---
=> Display transporter siret

src/sheets/rendering_helpers.py
=> Corrige une requête lente identifiée par le monitoring

src/sheets/admin.py, src/sheets/models.py
=> Reduce queries in django admin

src/sheets/models.py, src/sheets/rendering_helpers.py
=> Fix slow query

src/sheets/rendering_helpers.py
=> Fix optimization

src/templates/roadcontrol/partials/_bsd_card.html
Tronque les noms d'etablissements trop longs
---
=> Truncate long company names

src/templates/sheets/components/gistrid_stats_table.html
Petite PR pour corriger des fautes de français.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15013)
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15320)
=> Correction de fautes grammaticales 

src/roadcontrol/views.py
=> Remove forgotten breakpoint

src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/queries.py, src/sheets/tests/test_incinerator_outgoing_waste_processor.py, src/sheets/tests/test_rndts_quantities_graph_processor.py, src/sheets/tests/test_rndts_statements_graph_processor.py, src/sheets/tests/test_ssd_processor.py, src/sheets/tests/test_waste_flows_table_processor.py, src/sheets/tests/test_waste_processing_without_icpe_rubrique_processor.py, src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
Le nouveau dump RNDTS a changé le schéma de données précédent, cette PR fait les modifications nécessaires pour que la fiche puisse fonctionner.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15406)
=> Adaptation suite aux modifications du schéma de données RNDTS

src/sheets/graph_processors/plotly_components_processors.py
=> Correction d'un problème lié à un mauvais format de retour 

src/sheets/graph_processors/html_components_processors.py, src/sheets/tests/expected/incinerator_outgoing_waste_build_data_expected.json, src/sheets/tests/test_incinerator_outgoing_waste_processor.py
Des valeurs manquantes n'étaient pas traitées et causaient des problèmes lors de l'enregistrement des données en base.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15499)
=> Corrige un bug sur le IncineratorOutgoingWasteProcessor

Aptfile
=> Add aptfile

src/bin/post_compile
=> Gis env variables

.slugignore
=> Add slugignore

Aptfile
=> Fix aptfile

bin/post_compile
=> Fix manage path

Pipfile.lock, src/accounts/forms.py, src/aiot_provider/tests/test_allauth_disabled_views.py, src/roadcontrol/tests/test_converters.py, src/sheets/data_processing.py, src/sheets/graph_processors/html_components_processors.py, src/sheets/graph_processors/plotly_components_processors.py, src/sheets/tests/test_icpe_annual_item_processor.py
=> Mise à jour de dépendances

src/registry/forms.py, src/sheets/tests/test_quantity_outliers_table.py, src/templates/registry/registry_prepare.html, src/templates/scripts/registry_form_submit.html, src/templates/sheets/components/quantity_outliers_table.html
Améliorations de recette:
- Affichage de xls en premier choix
- Affichage d'un message et désactivation du bouton de soumission de formulaire en attendant de passer à un téléchargement asynchrone
https://github.com/user-attachments/assets/a3080c16-767f-4a76-bee1-1984eea95dc5
---
=> Improve registry download form

.env.dist, .github/workflows/main.yml, src/config/context_processors.py, src/config/settings/base.py, src/templates/sheets/sheet.html, src/templates/sheets/sheetpdf.html
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15901)
=> Mise à jour de la date de dernière mise à jour des sources de données.

src/accounts/models.py, src/accounts/tests/test_views.py
=> Fix access perms for CTT

src/templates/emails/second_factor/second_factor.html
=> Correction template email

src/sheets/graph_processors/html_components_processors.py, src/sheets/tests/test_waste_processing_without_icpe_rubrique_processor.py
Un bug est apparu suite à l'ajout de la quantité refusée dans le cas où le processor ne recevait que des types de bordereaux sans la colonne `quantity_refused`.
Le composant a été mis à jour.
Les tests ont été mis à jour.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-15941)
=> Correction d'un bug sur le composant WasteProcessingWithoutICPERubrique processor

src/templates/base.html
Le dropdown ne fonctionnait pas pour les utilisateurs venant de monaiot
---
=> Fix dropdown script

src/accounts/menus.py, src/accounts/models.py, src/accounts/tests/test_home.py, src/accounts/tests/test_views.py, src/conftest.py, src/data_exports/tests/test_views.py, src/data_exports/views.py, src/sheets/tests/test_views.py
L’administration centrale a désormais accès aux pages observatoires
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-15894)
=> Allow administration centrale to access data exports

src/oidc/urls.py
=> Fix callback url

.env.dist, src/templates/oidc/monaiot_authentication_error.html, src/templates/oidc/proconnect_authentication_error.html
Correction des templates d'erreur open id
---
=> Fix oidc error pages

.github/workflows/main.yml, src/api/serializers.py, src/sheets/forms.py, src/sheets/tests/test_icpe_annual_item_processor.py
=> Hotfix: api siret checks

Pipfile, Pipfile.lock, src/config/settings/base.py, src/sheets/admin.py
Ajoute des fonctionnalités de recherche à l'admin des feuilles d'établissements.
- recherche par ID
- recherche par date range
---
=> Recherche améliorée des fiches établissements dans l'admin

src/config/settings/production.py
=> Fix django vite config

src/templates/base.html
=> Plotly might be useful sometimes

src/static/ui_app_ts/src/App.tsx
=> Remove dynamic laoding

src/maps/management/commands/retrieve_companies.py
=> Paginate query

bin/post_compile
=> Fix deploy with new scalingo stack

Aptfile
=> Try again to fix deployment with aptfile

Aptfile
=> Let's try again

Aptfile, bin/post_compile
=> Another try

src/roadcontrol/forms.py
La création du tunnel ssh était manquante.
---
=> Ajout du tunnel ssh pour roadcontrol

src/static/ui_app_ts/src/constants/departments.ts
Because Normandie matters…
---
=> Add missing region on map UI

cron.json, src/accounts/management/commands/household.py
On est limités à 5 crons par scalingo, ajout d'une commande qui groupe les tâches de nettoyage
---
=> Add common household command

cron.json, src/registry/management/commands/refresh_export_states.py, src/registry/tests/test_command.py
=> Fix cron and command

src/registry/task.py
=> Fix setting access

src/accounts/menus.py, src/config/dashboard.py, src/config/settings/base.py
- correctif d'affichage sur le menu
- accès au objets sites dans l'admin (pour maj l'url des emails de 2fa)
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-16423)
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-16422)
=> Correctifs sur la mise en surbirllance du menu

src/sheets/data_processing.py
Correctif d'un bug sur les FI quand l'adresse est null
---
=> Fix null values in company adresses

cron.json
=> Maj du cron de récupération des companies

cron.json
=> Deactivate companies cron

src/maps/tests/test_views.py, src/maps/views.py
L'accès à la cartographie était réservée au staff TD, on l'ouvre à tous les profils
---
=> Allow cartography access to relevant profiles

src/templates/emails/base_email.html, src/templates/maps/icpe_map.html
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-16472)
=> Maj wording légende carte icpe

src/api/task.py, src/sheets/rendering_helpers.py
=> Put every task on the web queue

CONTRIBUTING.md
Un peu de doc pour la bannière
---
=> Add some user doc

Procfile, src/accounts/views.py, src/api/task.py, src/config/settings/base.py, src/registry/task.py, src/roadcontrol/task.py, src/sheets/task.py
- Passage a une queue celery unique
- ajout de l'affichage en console du code connexion (en DEBUG) pour éviter d'avoir à chercher dans le mail
---
=> Passage a une queue celery unique

Pipfile, Pipfile.lock
=> Ajoute pyarrow

src/templates/sheets/sheet_prepare.html
=> Fix sheet preparation template

changelog.md, src/sheets/graph_processors/html_components_processors.py
Le processor plantait en cas de DataFrame vide et de type non inféré.
---
=> Correction d'un problème sur le WasteFlowsTableProcessor

src/templates/maps/icpe_map.html
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-16808)
=> Rétablit la rubrique 2771 dans la cartographie des ICPE

src/sheets/graph_processors/html_components_processors.py
Il manquait un paramètre à l'appel de la fonction `map_elements`.
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-16894)
=> Corrige un problème sur le ICPEItemsProcessor

src/config/settings/base.py
---
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/37a331c647a38a191b2a1207?card=tra-17173)
=> Increase otp throttling factor
